name = "ai-drama-api"
main = "web/functions/api/[[route]].js"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "AI-戏剧-数据库"
database_id = "655999c0-8c60-48bb-8500-120133b23677"
